#!/bin/bash

set -o errexit -o pipefail -o posix
real_user=$SUDO_USER
set -o nounset

# algorithm:
# - create /etc/lockmachine_message
# - change /etc/passwd to run /etc/lockmachine_message at login for every user except caller and root

lock_filename=/etc/lockmachine_message

prog=$(basename $0)

if [ $prog == "lockmachine" ]; then

	dt=$(date)

	if [ $# -lt 1 ]; then
		echo "Locks the machine to prevent other users from logging in"
		echo "Usage: sudo $0 <message>"
		exit 1
	fi

	if [[ $real_user == "" || $UID -ne 0 ]]; then
		echo "Locks the machine to prevent other users from logging in"
		echo "Usage: sudo $0 <message>"
		exit 2
	fi

	echo "locked by user '$real_user' at $dt"

	echo -e "#!/bin/bash\n" > $lock_filename
	echo "echo \"locked by user '$real_user' at $dt\"" >> $lock_filename
	echo "echo \"$@\"" >> $lock_filename
	echo 'exit' >> $lock_filename

	chmod a+x $lock_filename

	IFS='
	'
	for user in $( < /etc/passwd ); do
		username=$(echo $user | awk 'BEGIN{FS=":"}{print $1}' )
		usershell=$(echo $user | awk 'BEGIN{FS=":"}{print $7}' )
		if [[ $username != "root" && $username != $real_user && $usershell == "/bin/bash" ]]; then
			echo "locking user '$username'"
			usermod -s $lock_filename $username
		fi
	done

else

	if [[ $UID -ne 0 || $# -ne 0 ]]; then
		echo "Unlocks the machine from a previous lockmachine call"
		echo "Usage: sudo $0"
		exit 2
	fi

	rm -f $lock_filename

	IFS='
	'
	for user in $( < /etc/passwd ); do
			username=$(echo $user | awk 'BEGIN{FS=":"}{print $1}' )
			usershell=$(echo $user | awk 'BEGIN{FS=":"}{print $7}' )
			if [[ $usershell == $lock_filename ]]; then
					echo "unlocking user '$username'"
					usermod -s /bin/bash $username
			fi
	done

fi
